package:
  name: ccfits
  version: 2.5

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}

  host:
    - cfitsio

  run:
    - cfitsio

about:
  home: http://heasarc.gsfc.nasa.gov/docs/software/fitsio/ccfits/

