package:
  name: xspec-modelsonly
  version: 12.10.0e

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  
  host:
    - ncurses

  run:
    - ncurses

about:
  home: https://heasarc.gsfc.nasa.gov/xanadu/xspec/

