package:
  name: xspec-modelsonly
  version: 12.10.0e

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - ncurses 5.*
    - readline
  
  host:
    - ncurses 5.*
    - readline

  run:
    - ncurses 5.*
    - readline

about:
  home: https://heasarc.gsfc.nasa.gov/xanadu/xspec/

