package:
  name: xspec-modelsonly
  version: 12.9.1u

requirements:
  build:
    - libgcc-ng
    - libgfortran-ng
    - ccfits
    - cfitsio

  run:
    - libgcc-ng
    - libgfortran-ng
    - ccfits
    - cfitsio

about:
  home: https://heasarc.gsfc.nasa.gov/xanadu/xspec/

