package:
  name: xspec-modelsonly
  version: 12.9.1u

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  
  host:
    - ccfits
    - cfitsio
    - wcslib
    - ncurses
    - readline

  run:
    - ccfits
    - cfitsio
    - wcslib
    - ncurses
    - readline

about:
  home: https://heasarc.gsfc.nasa.gov/xanadu/xspec/

