package:
  name: cfitsio
  version: 3.370

source:
  url: ftp://heasarc.gsfc.nasa.gov/software/fitsio/c/cfitsio3370.tar.gz 

build:
  number: 1

requirements:
  build:
   - {{ compiler('c') }}

about:
  home: http://heasarc.gsfc.nasa.gov/fitsio/fitsio.html

